You can define liquibase configuration for each datasource. The following example demonstrates using it:

[source, yaml]
.src/main/resources/application.yml
----
include::{liquibasetests}/groovy/io/micronaut/configuration/dbmigration/liquibase/LiquibaseSpec.groovy[tag=yamlconfig,indent=0]
----

<1> Disable schema DDL creation.
<2> Define all liquibase configuration under key `liquibase.datasources`.
<3> Configure liquibase configuration for `default` data source.
<4> Root changelog under `src/main/resources/db/liquibase-changelog.xml`.


Often, you will have a root changelog:

[source, xml]
.resources/db/liquibase-changelog.xml
----
include::{liquibasetests}/resources/db/liquibase-changelog.xml[indent=0]
----

which imports changelogs which you keep generating as your app evolves:

[source, xml]
.resources/db/changelog/01-create-books-schema.xml
----
include::{liquibasetests}/resources/db/changelog/01-create-books-schema.xml[indent=0]
----

NOTE: Liquibase migrations are executed when datasources are created. Because Micronaut beans are, by default, created
lazily, if you do not inject a `Datasource` somewhere, then migrations are not executed.
This may be the case when you create a command in a separate module just to run migrations, e.g. using Micronaut support
for https://docs.micronaut.io/latest/guide/index.html#commandLineApps[picocli].
In this case it is enough to inject a `Datasource` in anyone of your singletons and migrations will be executed.


There are several options available for configuration:

include::{includedir}configurationProperties/io.micronaut.configuration.dbmigration.liquibase.LiquibaseConfigurationProperties.adoc[]
