You can define liquibase configuration for each datasource. The following example demonstrates using it:

[configuration]
----
include::{liquibasetests}/groovy/io/micronaut/liquibase/docs/LiquibaseSpec.groovy[tag=yamlconfig,indent=0]
----

- `properties.hibernate.hbm2ddl.auto` set to `none` disables schema DDL creation.
- `liquibase.datasources` defines all liquibase configurations, for example `defauilt` in the example.]
- The root changelog is `src/main/resources/db/liquibase-changelog.xml`.

Often, you will have a root changelog:

[source, xml]
.resources/db/liquibase-changelog.xml
----
include::{liquibasetests}/resources/db/liquibase-changelog.xml[indent=0]
----

which imports changelogs which you keep generating as your app evolves:

[source, xml]
.resources/db/changelog/01-create-books-schema.xml
----
include::{liquibasetests}/resources/db/changelog/01-create-books-schema.xml[indent=0]
----

NOTE: Liquibase migrations are executed when datasources are created. Because Micronaut beans are, by default, created
lazily, if you do not inject a `Datasource` somewhere, then migrations are not executed.
This may be the case when you create a command in a separate module just to run migrations, e.g. using Micronaut support
for https://docs.micronaut.io/latest/guide/index.html#commandLineApps[picocli].
In this case it is enough to inject a `Datasource` in anyone of your singletons and migrations will be executed.

== Run migrations manually

If you need more control to decide when the migrations are executed it is possible to configure the application like this:

[configuration]
----
liquibase:
  enabled: true
  datasources:
    default:
      enabled: false
----

- Liquibase needs to be enabled
- Liquibase migrations can be disabled for a specific datasource

Now you can inject the `LiquibaseMigrator` bean and call manually the method `run` to execute the migrations when you want.


There are several options available for configuration:

include::{includedir}configurationProperties/io.micronaut.liquibase.LiquibaseConfigurationProperties.adoc[]



