
There is also support for running Liquibase migrations when using GORM.

1.- Add the dependency:

dependency:micronaut-hibernate-gorm[groupId="io.micronaut.groovy"]

2.- You also need at least one class annotated with `@grails.gorm.annotation.Entity` to trigger the migrations.
[source, groovy]
.src/main/groovy/example/Book.groovy
----
package example

include::{liquibasetests}/groovy/io/micronaut/liquibase/docs/Book.groovy[tag=clazz]
----

3.- Then it is necessary to configure GORM datasource:

[source, yaml]
.src/main/resources/application.yml
----
include::{liquibasetests}/groovy/io/micronaut/liquibase/docs/GormSpec.groovy[tag=yamlconfig,indent=0]
----

<1> Definition of the first data source in GORM. The name it's `default` and it can't be changed.
<2> Disable schema DDL creation.
<3> Define liquibase configuration under `liquibase.datasources` key.
<4> Define liquibase configuration for the `default` datasource.
<5> The migration file path is `src/main/resources/db/liquibase-changelog.xml`.


=== Multiple Data sources

It is also possible to configure Liquibase migrations with multiple data sources when using GORM:

[source, yaml]
.src/main/resources/application.yml
----
include::{liquibasetests}/groovy/io/micronaut/liquibase/docs/GormMultipleDataSourcesSpec.groovy[tag=yamlconfig,indent=0]
----

<1> Definition of the first data source in GORM. The name it's `default` and it can't be changed.
<2> Name of the additional data source.
<3> Define liquibase configuration for the `default` datasource.
<4> Define liquibase configuration for the `books` datasource.


NOTE: For more information about how to configure GORM, take a look at the http://gorm.grails.org/latest/hibernate/manual/index.html[documentation].

