
There is also support for running Liquibase migrations when using GORM.

1.- Add the dependency:

dependency:micronaut-hibernate-gorm[groupId="io.micronaut.groovy"]

2.- You also need at least one class annotated with `@grails.gorm.annotation.Entity` to trigger the migrations.
[source, groovy]
.src/main/groovy/example/Book.groovy
----
package example

include::{liquibasetests}/groovy/io/micronaut/liquibase/docs/Book.groovy[tag=clazz]
----

3.- Then it is necessary to configure GORM datasource:

[configuration]
----
include::{liquibasetests}/groovy/io/micronaut/liquibase/docs/GormSpec.groovy[tag=yamlconfig,indent=0]
----

- `dataSource` defines the first data source in GORM. The name is `default` and can't be changed.
- `dbCreate` set to `none` disables schema DDL creation.
- Define liquibase configuration under `liquibase.datasources`.
- Define liquibase configuration for the `default` datasource.
- The migration file path is set `src/main/resources/db/liquibase-changelog.xml`.


=== Multiple Data sources

It is also possible to configure Liquibase migrations with multiple data sources when using GORM:

[configuration]
----
include::{liquibasetests}/groovy/io/micronaut/liquibase/docs/GormMultipleDataSourcesSpec.groovy[tag=yamlconfig,indent=0]
----

- `dataSource` defines the first data source in GORM. The name is `default` and can't be changed.
- `dataSources.books` names an additional data source
- `liquibase.dataSources` defines the configurations for the datasources (i.e. default and books)

NOTE: For more information about how to configure GORM, take a look at the http://gorm.grails.org/latest/hibernate/manual/index.html[documentation].

