micronaut:
  application:
    name: micronaut-liquibase-graal
datasources:
  default:
    db-type: mariadb
    schema-generate: NONE
    dialect: MYSQL
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
---
endpoints:
  liquibase:
    enabled: true
    sensitive: false
