[versions]
managed-liquibase = "5.0.2"
commons-lang3 = "3.18.0"

micronaut = "5.0.0-M24"
micronaut-test = "5.0.0-M3"
micronaut-groovy = "5.0.0-M1"
micronaut-serde = "3.0.0-M7"
micronaut-sql = "7.0.1-M2"
micronaut-data = "5.0.0-M6"
micronaut-validation = "5.0.0-M2"
micronaut-gradle-plugin = "4.6.2"
micronaut-logging = "1.7.1"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

managed-liquibase = { module = "org.liquibase:liquibase-core", version.ref = "managed-liquibase" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }

micronaut-groovy = { module = "io.micronaut.groovy:micronaut-groovy-bom", version.ref = "micronaut-groovy" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }
micronaut-data = { module = "io.micronaut.data:micronaut-data-bom", version.ref = "micronaut-data" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
groovy-sql = { module = "org.apache.groovy:groovy-sql" }

h2 = { module = "com.h2database:h2" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter"}
testcontainers-mariadb = { module = "org.testcontainers:testcontainers-mariadb" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
