[versions]
managed-liquibase = "4.18.0"

gorm-hibernate = "7.3.0"
persistence-api = '2.2'
micronaut-gradle-plugin = "3.7.8"

[libraries]
managed-liquibase = { module = "org.liquibase:liquibase-core", version.ref = "managed-liquibase" }

micronaut-hibernate-gorm = { module = "io.micronaut.groovy:micronaut-hibernate-gorm" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client" }
micronaut-http-server-netty = { module = "io.micronaut:micronaut-http-server-netty" }
micronaut-inject-java = { module = 'io.micronaut:micronaut-inject-java' }
micronaut-jdbc = { module = "io.micronaut.sql:micronaut-jdbc" }
micronaut-jdbc-hikari = { module = "io.micronaut.sql:micronaut-jdbc-hikari" }
micronaut-management = { module = "io.micronaut:micronaut-management" }
micronaut-serde-api = { module = "io.micronaut.serde:micronaut-serde-api" }
micronaut-serde-processor = { module = "io.micronaut.serde:micronaut-serde-processor" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson" }

grails-datastore-gorm-hibernate5 = { module = "org.grails:grails-datastore-gorm-hibernate5", version.ref = "gorm-hibernate" }

groovy-sql = { module = "org.codehaus.groovy:groovy-sql" }

h2 = { module = "com.h2database:h2" }

persistence-api = { module = 'javax.persistence:javax.persistence-api', version.ref = 'persistence-api'}
projectreactor = { module = 'io.projectreactor:reactor-core' }
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
