[versions]
managed-liquibase = "4.32.0"

micronaut = "4.9.10"
micronaut-test = "4.7.0"
micronaut-testresources = "2.8.0"
micronaut-docs = "2.0.0"
groovy = "4.0.24"
spock = "2.3-groovy-4.0"

micronaut-groovy = "4.7.0"
micronaut-serde = "2.15.0"
micronaut-sql = "6.2.0"
micronaut-data = "4.12.2"
micronaut-validation = "4.9.0"
persistence-api = '2.2'

micronaut-gradle-plugin = "4.5.3"
micronaut-logging = "1.7.0"
sonatype-scan = "3.1.3"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

managed-liquibase = { module = "org.liquibase:liquibase-core", version.ref = "managed-liquibase" }

micronaut-groovy = { module = "io.micronaut.groovy:micronaut-groovy-bom", version.ref = "micronaut-groovy" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }
micronaut-data = { module = "io.micronaut.data:micronaut-data-bom", version.ref = "micronaut-data" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
micronaut-testresources = { module = 'io.micronaut.testresources:micronaut-test-resources-bom', version.ref = "micronaut-testresources" }
groovy-sql = { module = "org.apache.groovy:groovy-sql" }

h2 = { module = "com.h2database:h2" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter"}
persistence-api = { module = 'javax.persistence:javax.persistence-api', version.ref = 'persistence-api'}
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
sonatype-scan = { module = "org.sonatype.gradle.plugins:scan-gradle-plugin", version.ref = "sonatype-scan" }
