plugins {
    id("io.micronaut.build.internal.liquibase-module")
}

dependencies {
    annotationProcessor(mnSerde.micronaut.serde.processor)
    compileOnly mn.micronaut.inject.java
    compileOnly(mnSerde.micronaut.serde.api)
    compileOnly(mnSerde.micronaut.serde.jackson)

    // TODO: There is vulnerability in commons-lang3 3.17.0 coming via liquibase-core https://github.com/advisories/GHSA-j288-q9x7-2f5v
    // So the org.apache.commons:commons-lang3 exclusion is temporary workaround until fixed in liquibase when it should be removed
    api (libs.managed.liquibase) {
        exclude group: 'org.springframework'
        exclude group: 'org.apache.commons', module: 'commons-lang3'
    }
    api(libs.commons.lang3)

    api mn.micronaut.management
    api mnSql.micronaut.jdbc

    implementation mn.reactor

    testAnnotationProcessor libs.groovy.sql
    testAnnotationProcessor libs.persistence.api

    testImplementation mn.micronaut.inject.java
    testImplementation mn.micronaut.http.client
    testImplementation mn.micronaut.http.server.netty
    testImplementation mnSql.micronaut.jdbc.hikari
    testImplementation libs.groovy.sql

    testImplementation mnSql.h2
    testImplementation(mnSerde.micronaut.serde.jackson)
}
