micronaut:
  application:
    name: micronaut-liquibase-graal
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: dbuser
    password: 'theSecretPassword'
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: NONE
    dialect: POSTGRES
liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'
---
endpoints:
  liquibase:
    enabled: true
    sensitive: false
