# Micronaut Books DataSource
datasources.default.dialect=H2
datasources.default.schema-generate=NONE
liquibase.datasources.default.change-log=classpath\:db/liquibase-changelog.xml

# Grails Books DataSource
datasources.grails.dialect=H2
datasources.grails.schema-generate=NONE
liquibase.datasources.grails.change-log=classpath\:db/liquibase-changelog.xml
